-- MySQL Script generated by MySQL Workbench
-- Sun Mar  8 15:34:55 20

-- -----------------------------------------------------
-- Table `ville`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ville` ;

CREATE TABLE IF NOT EXISTS `ville` (
  `idVille` INT NOT NULL AUTO_INCREMENT,
  `nomVille` VARCHAR(255) NULL,
  `codePostale` VARCHAR(45) NULL,
  PRIMARY KEY (`idVille`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `image` ;

CREATE TABLE IF NOT EXISTS `image` (
  `idimage` INT NOT NULL AUTO_INCREMENT ,
  `lien` VARCHAR(45) NULL,
  PRIMARY KEY (`idimage`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `telephone` VARCHAR(45) NULL,
  `dateInscription` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
  `password` VARCHAR(2000) NULL,
  `admin` INT(1) NULL,
  `ville_idVille` INT NOT NULL,
  `image_idimage` INT NOT NULL,
  PRIMARY KEY (`iduser`),
    FOREIGN KEY (`ville_idVille`)
    REFERENCES `ville` (`idVille`),
    FOREIGN KEY (`image_idimage`)
    REFERENCES `image` (`idimage`)
  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `categorie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `categorie` ;

CREATE TABLE IF NOT EXISTS `categorie` (
  `idcategorie` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`idcategorie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sousCategorie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sousCategorie` ;

CREATE TABLE IF NOT EXISTS `sousCategorie` (
  `id_sousCategorie` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `id_categorie` INT NOT NULL,
  PRIMARY KEY (`id_sousCategorie`),
    FOREIGN KEY (`id_categorie`)
    REFERENCES `categorie` (`idcategorie`)
    )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `annonce`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `annonce` ;

CREATE TABLE IF NOT EXISTS `annonce` (
  `idarticle` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(45) NULL,
  `description` VARCHAR(2550) NULL,
  `prix` INT NULL,
  `datePublication` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
  `user_iduser` INT NOT NULL,
  `sponsorise` INT NULL,
  `sous_categorie_id` INT NOT NULL,
  `image_idimage` INT NOT NULL,
  PRIMARY KEY (`idarticle`, `user_iduser`, `sous_categorie_id`),
    FOREIGN KEY (`user_iduser`)
    REFERENCES `user` (`iduser`),
    FOREIGN KEY (`sous_categorie_id`)
    REFERENCES `sousCategorie` (`id_sousCategorie`),
    FOREIGN KEY (`image_idimage`)
    REFERENCES `image` (`idimage`)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `favoris`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `favoris` ;

CREATE TABLE IF NOT EXISTS `favoris` (
  `idfavoris` INT NOT NULL AUTO_INCREMENT,
  `user_iduser` INT NOT NULL,
  `annonce_idarticle` INT NOT NULL,
  PRIMARY KEY (`idfavoris`, `user_iduser`, `annonce_idarticle`),
    FOREIGN KEY (`user_iduser`)
    REFERENCES `user` (`iduser`),
    FOREIGN KEY (`annonce_idarticle`)
    REFERENCES `annonce` (`idarticle`)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `message` ;

CREATE TABLE IF NOT EXISTS `message` (
  `idmessage` INT NOT NULL AUTO_INCREMENT,
  `annonce_idarticle` INT NOT NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`idmessage`, `annonce_idarticle`, `user_iduser`),
    FOREIGN KEY (`annonce_idarticle`)
    REFERENCES `annonce` (`idarticle`),
    FOREIGN KEY (`user_iduser`)
    REFERENCES `user` (`iduser`)
    )
ENGINE = InnoDB;

 ;

-- -----------------------------------------------------
-- Placeholder table for view `view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `view1` (`id` INT);

-- -----------------------------------------------------
-- View `view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `view1`;
DROP VIEW IF EXISTS `view1` ;




